In [14]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.shape)

(5,)


In [15]:
arr2 = arr.reshape(1,5)
arr2.shape

(1, 5)

In [26]:
np.arange(0,10,3).reshape(1, 4)
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
## Identity array - Only diagonal is 1 and rest is 0

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [63]:
## numpy vectorized operations

# Create a 4x5 array with multiple rows of numbers
arr3 = np.array([[1,2,3,4,5], [3,4,5,6,7], [5,6,7,8,9], [10,11,12,13,14]])
print(arr3)  # Print the full array

# Array slicing with arr3[1:3,2:] means:
# - Rows 1 to 3 (excluding 3) - so rows 1 and 2
# - Columns 2 onwards (2 to end)
# This will return a 2x3 array containing elements [5,6,7] and [7,8,9]
arr3[1:3,2:]

[[ 1  2  3  4  5]
 [ 3  4  5  6  7]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


array([[5, 6, 7],
       [7, 8, 9]])